
import __ASTRO_IMAGE_IMPORT_ZcKpc2 from '../assets/captures/trucomatic.png?astroContentImageFlag=&importer=src%2Fprojects%2F01-trucomatic.md';
import __ASTRO_IMAGE_IMPORT_opxoS from '../assets/logo/trucomatic.svg?astroContentImageFlag=&importer=src%2Fprojects%2F01-trucomatic.md';
import __ASTRO_IMAGE_IMPORT_Z2fEO9w from '../assets/captures/eduactivo.png?astroContentImageFlag=&importer=src%2Fprojects%2F02-eduactivo.md';
import __ASTRO_IMAGE_IMPORT_1OHV6W from '../assets/logo/eduactivo.svg?astroContentImageFlag=&importer=src%2Fprojects%2F02-eduactivo.md';
import __ASTRO_IMAGE_IMPORT_Y3Edi from '../assets/captures/score.png?astroContentImageFlag=&importer=src%2Fprojects%2F04-score.md';
import __ASTRO_IMAGE_IMPORT_Z1hgX1d from '../assets/logo/score.svg?astroContentImageFlag=&importer=src%2Fprojects%2F04-score.md';
import __ASTRO_IMAGE_IMPORT_Z6dM0r from '../assets/logo/peon.svg?astroContentImageFlag=&importer=src%2Fprojects%2F03-peon.md';
import __ASTRO_IMAGE_IMPORT_lqd1o from '../assets/captures/peon.png?astroContentImageFlag=&importer=src%2Fprojects%2F03-peon.md';
export default new Map([["../assets/captures/trucomatic.png?astroContentImageFlag=&importer=src%2Fprojects%2F01-trucomatic.md", __ASTRO_IMAGE_IMPORT_ZcKpc2], ["../assets/logo/trucomatic.svg?astroContentImageFlag=&importer=src%2Fprojects%2F01-trucomatic.md", __ASTRO_IMAGE_IMPORT_opxoS], ["../assets/captures/eduactivo.png?astroContentImageFlag=&importer=src%2Fprojects%2F02-eduactivo.md", __ASTRO_IMAGE_IMPORT_Z2fEO9w], ["../assets/logo/eduactivo.svg?astroContentImageFlag=&importer=src%2Fprojects%2F02-eduactivo.md", __ASTRO_IMAGE_IMPORT_1OHV6W], ["../assets/captures/score.png?astroContentImageFlag=&importer=src%2Fprojects%2F04-score.md", __ASTRO_IMAGE_IMPORT_Y3Edi], ["../assets/logo/score.svg?astroContentImageFlag=&importer=src%2Fprojects%2F04-score.md", __ASTRO_IMAGE_IMPORT_Z1hgX1d], ["../assets/logo/peon.svg?astroContentImageFlag=&importer=src%2Fprojects%2F03-peon.md", __ASTRO_IMAGE_IMPORT_Z6dM0r], ["../assets/captures/peon.png?astroContentImageFlag=&importer=src%2Fprojects%2F03-peon.md", __ASTRO_IMAGE_IMPORT_lqd1o]]);
		